
import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class game extends javax.swing.JFrame {
static int p=0,g,c=0;
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        if(p==1){
            s1.setText("Bowling");
            s2.setText("Batting");
        }
    }
    void comp(){
        Random r=new Random();
                   int rs=r.nextInt(6);
        if(rs==0){
            ImageIcon im=new ImageIcon(getClass().getResource("/1.jpeg"));
Image newimg=im.getImage().getScaledInstance(i1.getWidth(),i1.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i1.setIcon(image);
 g=1;}
        else if(rs==1){
            ImageIcon im=new ImageIcon(getClass().getResource("/2.jpeg"));
Image newimg=im.getImage().getScaledInstance(i1.getWidth(),i1.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i1.setIcon(image);
        g=2;}
        else if(rs==2){
            ImageIcon im=new ImageIcon(getClass().getResource("/3.jpeg"));
Image newimg=im.getImage().getScaledInstance(i1.getWidth(),i1.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i1.setIcon(image);
        g=3;}
        else if(rs==3){
            ImageIcon im=new ImageIcon(getClass().getResource("/4.jpeg"));
Image newimg=im.getImage().getScaledInstance(i1.getWidth(),i1.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i1.setIcon(image);
        g=4;}
        else if(rs==4){
            ImageIcon im=new ImageIcon(getClass().getResource("/5.jpeg"));
Image newimg=im.getImage().getScaledInstance(i1.getWidth(),i1.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i1.setIcon(image);
        g=5;}
        else{
            ImageIcon im=new ImageIcon(getClass().getResource("/6.jpeg"));
Image newimg=im.getImage().getScaledInstance(i1.getWidth(),i1.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i1.setIcon(image);
        g=6;}
    }
    void scr(int r){
            int a=Integer.parseInt(us.getText()),b=Integer.parseInt(cs.getText());
        if(rst.getText().equals("OUT"))
            rst.setText("");
        if(g==r)
        {if(c==1)
        {if(a>b)
            rst.setText("Utkarsh Wins");
        else if(b>a)
            rst.setText("Computer Wins");
        else
            rst.setText("Draw");
        rst.setForeground(Color.YELLOW);
        r1.setEnabled(false);
        r2.setEnabled(false);
        r3.setEnabled(false);
        r4.setEnabled(false);
        r5.setEnabled(false);
        r6.setEnabled(false);}
        else{
            rst.setText("OUT");
        rst.setForeground(Color.red);
        if(p==1){c++;
            p=0;
            s2.setText("Bowling");
            s1.setText("Batting");}
        else{c++;
            p=1;
            s1.setText("Bowling");
            s2.setText("Batting");
        }}}
       else if(p==0){
            int st=a+r;
            us.setText(""+st);}
       else{
           int st=b+g;
            cs.setText(""+st);}
        if(c==1&&(a>0||b>0)){
        if(a+r>b&&p==0)
        {rst.setText("Utkarsh Wins");
        r1.setEnabled(false);
        r2.setEnabled(false);
        r3.setEnabled(false);
        r4.setEnabled(false);
        r5.setEnabled(false);
        r6.setEnabled(false);}
        else if(b+g>a&&p==1)
        {rst.setText("Computer Wins");
        r1.setEnabled(false);
        r2.setEnabled(false);
        r3.setEnabled(false);
        r4.setEnabled(false);
        r5.setEnabled(false);
        r6.setEnabled(false);}}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        i1 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ns = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        r1 = new javax.swing.JButton();
        r2 = new javax.swing.JButton();
        r3 = new javax.swing.JButton();
        r4 = new javax.swing.JButton();
        r5 = new javax.swing.JButton();
        r6 = new javax.swing.JButton();
        n = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        rst = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("HAND CRICKET");

        i1.setBackground(new java.awt.Color(255, 255, 255));
        i1.setOpaque(true);

        i2.setBackground(new java.awt.Color(255, 255, 255));
        i2.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 35)); // NOI18N
        jLabel2.setText("Score Board");

        ns.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        ns.setText("Utkarsh Score");

        us.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        us.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        us.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel5.setText("Computer Score");

        cs.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setText("0");

        s1.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s1.setText("Batting");

        s2.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        s2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s2.setText("Bowling");

        r1.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        r1.setText("1 Run");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        r2.setText("2 Runs");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        r3.setText("3 Runs");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        r4.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        r4.setText("4 Runs");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        r5.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        r5.setText("5 Runs");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        r6.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        r6.setText("6 Runs");
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n.setText("Utkarsh");

        n1.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n1.setText("Computer");

        rst.setFont(new java.awt.Font("Tahoma", 1, 43)); // NOI18N
        rst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rst.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(r3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(r4))
                            .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r6)
                            .addComponent(r5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(85, 85, 85))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(88, 88, 88)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ns)
                                            .addComponent(jLabel2)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(rst, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(612, 612, 612)
                        .addComponent(jLabel1)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s2)
                            .addComponent(s1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rst, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(ns)
                        .addGap(41, 41, 41)
                        .addComponent(us)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(cs))
                    .addComponent(i1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(i2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r1)
                        .addComponent(r6)
                        .addComponent(n1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2)
                    .addComponent(r3)
                    .addComponent(r4)
                    .addComponent(r5))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
ImageIcon im=new ImageIcon(getClass().getResource("/one.jpeg"));
Image newimg=im.getImage().getScaledInstance(i2.getWidth(),i2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i2.setIcon(image);
 comp();
 scr(1);
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
ImageIcon im=new ImageIcon(getClass().getResource("/two.jpeg"));
Image newimg=im.getImage().getScaledInstance(i2.getWidth(),i2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i2.setIcon(image);
comp();
 scr(2);
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
ImageIcon im=new ImageIcon(getClass().getResource("/three.jpeg"));
Image newimg=im.getImage().getScaledInstance(i2.getWidth(),i2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i2.setIcon(image);
comp();
 scr(3);
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
ImageIcon im=new ImageIcon(getClass().getResource("/four.jpeg"));
Image newimg=im.getImage().getScaledInstance(i2.getWidth(),i2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i2.setIcon(image);
comp();
 scr(4);
    }//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
ImageIcon im=new ImageIcon(getClass().getResource("/five.jpeg"));
Image newimg=im.getImage().getScaledInstance(i2.getWidth(),i2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i2.setIcon(image);
comp();
 scr(5);
    }//GEN-LAST:event_r5ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
ImageIcon im=new ImageIcon(getClass().getResource("/six.jpeg"));
Image newimg=im.getImage().getScaledInstance(i2.getWidth(),i2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon image=new ImageIcon(newimg);
        i2.setIcon(image);
comp();
 scr(6);
    }//GEN-LAST:event_r6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cs;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel ns;
    private javax.swing.JButton r1;
    private javax.swing.JButton r2;
    private javax.swing.JButton r3;
    private javax.swing.JButton r4;
    private javax.swing.JButton r5;
    private javax.swing.JButton r6;
    private javax.swing.JLabel rst;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel us;
    // End of variables declaration//GEN-END:variables
}
